# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jcxB8oDzrHuZ8cWzwqfXEzweRpSIBJ-y
"""

import pandas as pd
data=pd.read_csv('/content/dummy_data_all_shuffled')
data.head()

data.isnull().sum()

data["fall"] = data["fall"].map({0: "ADL", 1: "Fall"})

x=data[['accelerometer_x','accelerometer_y','accelerometer_z','gyroscope_x','gyroscope_y','gyroscope_z']]
y=data['fall']

print((x))

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.20, random_state=42)

model=DecisionTreeClassifier()
model.fit(xtrain,ytrain)

prediction=model.predict(xtest)

from sklearn.metrics import confusion_matrix
confus=confusion_matrix(ytest,prediction)

from sklearn.metrics import classification_report
confus_report=classification_report(ytest,prediction)
confus_report